# This file stores secrets for your Streamlit app.
# Learn more at https://docs.streamlit.io/library/advanced-features/secrets-management

GOOGLE_API_KEY = "AQ.Ab8RN6I9kCjhcWfL86ePwLN38KwDanAFd-bnd1gP6Zcqf82giQ"